apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q3bpr0csq-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/q3bpr0csq-dotnet-basic